{"name": "test_holle2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_login.TestLogin object at 0x04110CB0>\n\n    def test_holle2(self):\n>       assert False\nE       assert False\n\nscripts\\test_login.py:7: AssertionError"}, "start": 1612402907884, "stop": 1612402907884, "uuid": "12c8fafc-ca01-47d8-a9bb-c021baffcdf0", "historyId": "c98a8622f8cedbfb67ddba52fc12c408", "testCaseId": "1071027049d42ad01cbf892279eb0e8c", "fullName": "scripts.test_login.TestLogin#test_holle2", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-5SSN07HR"}, {"name": "thread", "value": "20672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}